[project]
name = "modern-homelab"
version = "0.1.0"
description = "Homelab"
readme = "README.md"
authors = [
    { name = "sankalp6115", email = "sankalpomar6115@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "uvicorn>=0.53.0",
]

[project.scripts]
modern-homelab = "modern_homelab:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
